version: "2.3"
services:
  webjorge:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "../Source:/home"
    depends_on:
     - redis
  redis:
   image: redis:latest
